### ISSUE TITLE
import pyftdi.serialext not working

### ISSUE THREAD

**Issue by charkster** [eblot/pyftdi#289]
Hi, I'm using a FT2232H on a Raspberry Pi 4 64bit bullseye. I added my udev rules and am able to see my device:
```
from pyftdi.ftdi import Ftdi
Ftdi.show_devices()

Available interfaces:
  ftdi://ftdi:2232:210328AD3FF5/1   (Digilent Adept USB Device)
  ftdi://ftdi:2232:210328AD3FF5/2   (Digilent Adept USB Device)
```
I already had pyserial installed and checked the version:
```
pip3 show pyserial

Name: pyserial
Version: 3.5b0
Summary: Python Serial Port Extension
Home-page: https://github.com/pyserial/pyserial
Author: Chris Liechti
Author-email: cliechti@gmx.net
License: BSD
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: pyftdi, mote
```
I get an error when I try to import serialext:
```
import pyftdi.serialext
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pyftdi/serialext/__init__.py", line 16, in <module>
    version = tuple([int(x) for x in VERSION.split('.')])
  File "/home/pi/.local/lib/python3.9/site-packages/pyftdi/serialext/__init__.py", line 16, in <listcomp>
    version = tuple([int(x) for x in VERSION.split('.')])
ValueError: invalid literal for int() with base 10: '5b0'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.9/site-packages/pyftdi/serialext/__init__.py", line 20, in <module>
    raise ImportError("pyserial 3.0+ is required") from exc
ImportError: pyserial 3.0+ is required
```

Any ideas as to what I am doing wrong? Is it the fact that the pyserial version has a suffix of "b0"? I'll try to specify a different version of pyserial.
Thank you.

**Comment by charkster** [comment]
The pyserial version was my problem. I specifically installed 3.4 and now am working as expected.
`pip3 install pyserial=3.4`
