### ISSUE TITLE
Error coming while trying to import board

### ISSUE THREAD

**Issue by thedim-witted** [eblot/pyftdi#296]
Hi,

I went through the installation process and was able to detect the ft232h board using the ftdi library.

```
>>> from pyftdi.ftdi import Ftdi
>>> Ftdi().open_from_url('ftdi:///?')
Available interfaces:
  ftdi://ftdi:232h:1/1   (￿￿￿￿￿￿)
```

 However, it throws an error when I try to do a 'import board'
The error says:

>>> import board
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/devop1/.local/lib/python3.6/site-packages/board.py", line 39, in <module>
    import adafruit_platformdetect.constants.boards as ap_board
  File "/home/devop1/.local/lib/python3.6/site-packages/adafruit_platformdetect/__init__.py", line 10, in <module>
    from .board import Board
  File "/home/devop1/.local/lib/python3.6/site-packages/adafruit_platformdetect/board.py", line 24
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

**Comment by eblot** [comment]
This code is not part of PyFtdi. Please reach out the original project (Adafruit ?)
