### ISSUE TITLE
SPI Module Using GPIO Issue---OverflowError: unsigned byte integer is greater than maximum

### ISSUE THREAD

**Issue by lifetyper** [eblot/pyftdi#98]
I use below code to control AC4&AC7 as gpio and spi port with cs0,but got OverflowError.
Chip:FT232H
OS:MacOS High Sierra
Python:3.6.3

```
# coding=utf-8
from pyftdi.spi import SpiController
from time import sleep

spi = SpiController()
spi.configure(url="ftdi://ftdi:232h/1/")
pe = spi.get_port(cs=0, freq=1E6, mode=0)

# enable 5v output on ac7,seprate D1 D2 on ac4
print('config and set gpio')
gpio = spi.get_gpio()
gpio.set_direction(0x9000,0x9000)
gpio.write(0x9000)

print('spi write out')
pe.write([0x01,0x00])


```

Error Message Below:
```
Traceback (most recent call last):
  File "/Users/lifetyper/Dropbox/Python/Utils/bug.py", line 23, in <module>
    pe.write([0x01,0x00])
  File "/usr/local/lib/python3.6/site-packages/pyftdi/spi.py", line 143, in write
    self._cpol, self._cpha)
  File "/usr/local/lib/python3.6/site-packages/pyftdi/spi.py", line 384, in exchange
    cpol, cpha)
  File "/usr/local/lib/python3.6/site-packages/pyftdi/spi.py", line 492, in _exchange_half_duplex
    cmd.extend((Ftdi.SET_BITS_LOW, ctrl, direction))
OverflowError: unsigned byte integer is greater than maximum
```

But if I re-config spi controller and spi port after setting and using gpio port,everything works fine:

```
# coding=utf-8
from pyftdi.spi import SpiController
from time import sleep

spi = SpiController()
spi.configure(url="ftdi://ftdi:232h/1/")
pe = spi.get_port(cs=0, freq=1E6, mode=0)


# enable 5v output on ac7,seprate D1 D2 on ac4
print('config and set gpio')
gpio = spi.get_gpio()
gpio.set_direction(0x9000,0x9000)
gpio.write(0x9000)


# re-config spi after gpio will Solve this issue
spi = SpiController()
spi.configure(url="ftdi://ftdi:232h/1/")
pe = spi.get_port(cs=0, freq=1E6, mode=0)

print('spi write out')
pe.write([0x01,0x00])



```

But If I use gpio on ADBUS only,this issue won't happen,code below works fine
```
# coding=utf-8
from pyftdi.spi import SpiController
from time import sleep

spi = SpiController()
spi.configure(url="ftdi://ftdi:232h/1/")
pe = spi.get_port(cs=0, freq=1E6, mode=0)


# If I use only gpio on ADBUS,this works fine
print('config and set gpio')
gpio = spi.get_gpio()
gpio.set_direction(0x80,0x80)
gpio.write(0x80)

print('spi write out')
pe.write([0x01,0x00])


```

**Comment by eblot** [comment]
Line 492 is a comment in master branch. Which version are you actually using?

I think this issue has been fixed a couple of weeks ago, but it may not have been committed to the PyPi repository yet. I definitely should.

**Comment by lifetyper** [comment]
Well,I was using the latest version from PyPi,which is 0.28.3.
After changing pyftdi lib to 0.28.7 from github release,everything works fine.

As you said,you definitely should commit the latest code to PyPi 
😀

**Comment by eblot** [comment]
Sorry about that. It is now available on PyPI. Thanks for the report.
